# TCL File Generated by Component Editor 24.1
# Tue Jul 23 14:00:31 CEST 2024
# DO NOT MODIFY


# 
# control_stream_and_bridge "control_stream_and_bridge" v1.0
# KoKa  2024.07.23.14:00:31
# Bridge to mimic msgdma transfer of data
# 

# 
# request TCL package from ACDS 24.1
# 
package require -exact qsys 24.1


# 
# module control_stream_and_bridge
# 
set_module_property DESCRIPTION "Bridge to mimic msgdma transfer of data"
set_module_property NAME control_stream_and_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR "KoKa "
set_module_property DISPLAY_NAME control_stream_and_bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL control_stream_and_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file control_stream_and_bridge.v VERILOG PATH control_stream_and_bridge.v TOP_LEVEL_FILE
add_fileset_file controlled_statemachine.v VERILOG PATH controlled_statemachine.v
add_fileset_file csr_handler.v VERILOG PATH csr_handler.v
add_fileset_file led_blink_control.v VERILOG PATH led_blink_control.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL control_stream_and_bridge
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file control_stream_and_bridge.v VERILOG PATH control_stream_and_bridge.v
add_fileset_file controlled_statemachine.v VERILOG PATH controlled_statemachine.v
add_fileset_file csr_handler.v VERILOG PATH csr_handler.v
add_fileset_file led_blink_control.v VERILOG PATH led_blink_control.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point axi4stream_slave
# 
add_interface axi4stream_slave axi4stream end
set_interface_property axi4stream_slave associatedClock clock_sink
set_interface_property axi4stream_slave associatedReset reset_sink
set_interface_property axi4stream_slave ENABLED true
set_interface_property axi4stream_slave EXPORT_OF ""
set_interface_property axi4stream_slave PORT_NAME_MAP ""
set_interface_property axi4stream_slave CMSIS_SVD_VARIABLES ""
set_interface_property axi4stream_slave SVD_ADDRESS_GROUP ""
set_interface_property axi4stream_slave IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property axi4stream_slave SV_INTERFACE_TYPE ""
set_interface_property axi4stream_slave SV_INTERFACE_MODPORT_TYPE ""

add_interface_port axi4stream_slave axi4stream_slave_tdata tdata Input 24
add_interface_port axi4stream_slave axi4stream_slave_tready tready Output 1
add_interface_port axi4stream_slave axi4stream_slave_tuser tuser Input 3
add_interface_port axi4stream_slave axi4stream_slave_tvalid tvalid Input 1
add_interface_port axi4stream_slave axi4stream_slave_tlast tlast Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""
set_interface_property clock_sink IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock_sink SV_INTERFACE_TYPE ""
set_interface_property clock_sink SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock_sink clock_sink_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
set_interface_property reset_sink IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset_sink SV_INTERFACE_TYPE ""
set_interface_property reset_sink SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset_sink reset_sink_reset reset Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock_sink
set_interface_property avalon_streaming_source associatedReset reset_sink
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyAllowance 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""
set_interface_property avalon_streaming_source IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_streaming_source SV_INTERFACE_TYPE ""
set_interface_property avalon_streaming_source SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_streaming_source avalon_streaming_source_data data Output 24
add_interface_port avalon_streaming_source avalon_streaming_source_ready ready Input 1
add_interface_port avalon_streaming_source avalon_streaming_source_valid valid Output 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressGroup 0
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock_sink
set_interface_property csr associatedReset reset_sink
set_interface_property csr bitsPerSymbol 8
set_interface_property csr bridgedAddressOffset ""
set_interface_property csr bridgesToMaster ""
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr minimumResponseLatency 1
set_interface_property csr readLatency 1
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr transparentBridge false
set_interface_property csr waitrequestAllowance 0
set_interface_property csr writeWaitTime 0
set_interface_property csr dfhFeatureGuid 0
set_interface_property csr dfhGroupId 0
set_interface_property csr dfhParameterId ""
set_interface_property csr dfhParameterName ""
set_interface_property csr dfhParameterVersion ""
set_interface_property csr dfhParameterData ""
set_interface_property csr dfhParameterDataLength ""
set_interface_property csr dfhFeatureMajorVersion 0
set_interface_property csr dfhFeatureMinorVersion 0
set_interface_property csr dfhFeatureId 35
set_interface_property csr dfhFeatureType 3
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""
set_interface_property csr IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property csr SV_INTERFACE_TYPE ""
set_interface_property csr SV_INTERFACE_MODPORT_TYPE ""

add_interface_port csr csr_read read Input 1
add_interface_port csr csr_readdata readdata Output 32
add_interface_port csr csr_writedata writedata Input 32
add_interface_port csr csr_write write Input 1
add_interface_port csr csr_address address Input 8
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_blink
# 
add_interface conduit_blink conduit end
set_interface_property conduit_blink associatedClock clock_sink
set_interface_property conduit_blink associatedReset reset_sink
set_interface_property conduit_blink ENABLED true
set_interface_property conduit_blink EXPORT_OF ""
set_interface_property conduit_blink PORT_NAME_MAP ""
set_interface_property conduit_blink CMSIS_SVD_VARIABLES ""
set_interface_property conduit_blink SVD_ADDRESS_GROUP ""
set_interface_property conduit_blink IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit_blink SV_INTERFACE_TYPE ""
set_interface_property conduit_blink SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit_blink led_out_1 led_out_1 Output 1
add_interface_port conduit_blink led_out_2 led_out_2 Output 1

